#include "m_sysinfo.hpp"

#include <string>

#include "config.h" // generated by Cmake, template located "config.h.in"

namespace zeltrex {
    namespace info{
        sysinfo::sysinfo(/* args */)
        {
        }
        
        sysinfo::~sysinfo()
        {
        }
        std::string sysinfo::getOsName()
        {
            #ifdef _WIN32
            return "Windows 32-bit";
            #elif _WIN64
            return "Windows 64-bit";
            #elif __APPLE__ || __MACH__
            return "Mac OSX";
            #elif __linux__
            return "Linux";
            #elif __FreeBSD__
            return "FreeBSD";
            #elif __unix || __unix__
            return "Unix";
            #else
            return "Other";
            #endif
         }

        std::string sysinfo::getAppVersion()
        {
            std::string s;
            s = "Version " + std::to_string(VERSION_MAJOR) + "." + std::to_string(VERSION_MINOR);
            return s; 
         }
    }
}